# This file defines the principal settings for this project

REPO_NAME          := CHIPS
GRF_ID             := \"CHPS\"

TARGET_FILES       := chips.grf

# Uncomment those lines which are applicable
USE_NFO := 1

# If everything is default, you don't need the rest:

# comment out those dirs which are not in use
SRC_DIR            := sprites
DOC_DIR            := docs
SCRIPT_DIR         := scripts

# Add any dirs which shall be bundled in a source release additionally
# to the dirs mentioned above.
EXTRA_DIRS         :=

# separate dir for the (p)nfo files can be configured or set it to
# $(SRC_DIR) 
NFO_DIR            := $(SRC_DIR)/nfo

# Documentation files:
DOC_FILES = docs/readme.txt docs/license.txt docs/changelog.txt

# file extentions which indicate plain text source files, 
# parsable by a text editor
# FILE_SRC_EXTENSIONS = pnfo tnfo

# file extensions which indicate binary source files
# FILE_INC_EXTENSIONS = wav pcx png

# Replacement strings in the source and in the documentation
# You may only change the values, not add new definitions
# (unless you know where to add them in other places, too)
REPO_TITLE_DUMMY      := {{GRF_TITLE}}
GRF_ID_DUMMY          := {{GRF_ID}}
REPO_REVISION_DUMMY   := {{REPO_REVISION}}
OUTPUT_FILENAME_DUMMY := {{FILENAME}}
GRF_MD5SUM_DUMMY      := {{GRF_MD5}}

# List of all files which will get shipped
# DOC_FILES = readme, changelog and license
# GRF_FILENAME = MAIN_FILENAME_SRC with the extention .grf
# Add any additional, not usual files here, too, including
# their relative path to the root of the repository
BUNDLE_FILES           = $(TARGET_FILES) $(DOC_FILES)

# Files which also need cleaning:
CLEAN_ADD             := docs/readme.txt
