[GLOBAL_PRAGMA]
grflangid = "0x01"
plural = "0"

[STR_GRF_DESCRIPTION]
base = "CABBAGE"

["# {ORANGE}FIRS Industry Replacement Set{}{BLACK}Brought to you by andythenorth, FooBar, planetmaker, Terkhen and Yexo, with help from many others. {SILVER}See readme for more information, including how to use CHIPS. {BLACK}License"]
base = "GPL v2."

# station classes

# rail stations
[STR_NAME_STATION_CLASS_DFLT]
# default town stations go into the DFLT class, alongside the base game stations, and we also change the name string for that class
base = "Town stations (pavement)"

[STR_NAME_STATION_CLASS_INAS]
base = "Industry stations (asphalt)"

[STR_NAME_STATION_CLASS_INCO]
base = "Industry stations (cobble)"

[STR_NAME_STATION_CLASS_INDI]
base = "Industry stations (dirt)"

[STR_NAME_STATION_CLASS_INGR]
base = "Industry stations (gravel)"

# road stops
[STR_NAME_ROAD_STOP_CLASS_DFLT]
# !! CABBAGE - does DFLT work here? It's used by rail stations, but maybe that should be a remap?
base = "Road stops (pavement)"

[STR_NAME_ROAD_STOP_CLASS_INAS]
base = "Road stops (asphalt)"

[STR_NAME_ROAD_STOP_CLASS_INCO]
base = "Road stops (cobble)"

[STR_NAME_ROAD_STOP_CLASS_INDI]
base = "Road stops (dirt)"

[STR_NAME_ROAD_STOP_CLASS_INGR]
base = "Road stops (gravel)"

# objects
[STR_NAME_OBJECT_CLASS_DFLT]
# !! CABBAGE - does DFLT work here? It's used by rail stations, but maybe that should be a remap?
base = "Station facilities (pavement)"

[STR_NAME_OBJECT_CLASS_INAS]
base = "Station facilities (asphalt)"

[STR_NAME_OBJECT_CLASS_INCO]
base = "Station facilities (cobble)"

[STR_NAME_OBJECT_CLASS_INDI]
base = "Station facilities (dirt)"

[STR_NAME_OBJECT_CLASS_INGR]
base = "Station facilities (gravel)"

# station names, keep alphabetised by ID

[STR_NAME_STATION_BOILER_HOUSE_OFFICE]
base = "Boiler house & offices"

[STR_NAME_STATION_BOOKING_OFFICE]
base = "Booking office"

[STR_NAME_STATION_BOOKING_OFFICE_SMALL]
base = "Small booking office"

[STR_NAME_STATION_CARGO_VISIBLE_INDUSTRY]
base = "VISIBLE CARGO"

[STR_NAME_STATION_CARGO_VISIBLE_TOWN]
base = "VISIBLE CARGO"

[STR_NAME_STATION_CEMENT_SILO]
base = "Cement silo"

[STR_NAME_STATION_CONCOURSE_1]
base = "Passenger concourse"

[STR_NAME_STATION_DISPATCHERS_OFFICE]
base = "Dispatcher's office"

[STR_NAME_STATION_FLOOD_LOADER_SILO]
base = "Flood loader silo"

[STR_NAME_STATION_FOUNDRY_BUILDINGS]
base= "Foundry building"

[STR_NAME_STATION_HARBOUR_CRANE]
base = "Harbour crane"

[STR_NAME_STATION_HOTEL]
base = "Hotel"

[STR_NAME_STATION_HUTS]
base = "Hut"

[STR_NAME_STATION_MINE_BUILDINGS]
base = "Mine building"

[STR_NAME_STATION_PARCELS_OFFICE]
base = "Parcels office"

[STR_NAME_STATION_TEST]
base = "CABBAGE"

[STR_NAME_STATION_TIPPLE]
base = "Tipple"

[STR_NAME_STATION_WAREHOUSE_TOWN]
base = "Warehouse"


