[GLOBAL_PRAGMA]
grflangid = "0x01"
plural = "0"

[STR_GRF_DESCRIPTION]
base = "CABBAGE"

[STR_CABBAGE]
base = "CABBAGE"

["# {ORANGE}FIRS Industry Replacement Set{}{BLACK}Brought to you by andythenorth, FooBar, planetmaker, Terkhen and Yexo, with help from many others. {SILVER}See readme for more information, including how to use CHIPS. {BLACK}License"]
base = "GPL v2."

# company colours
[STR_PALETTE_USE_DEFAULT]
base = "company colour"

[STR_PALETTE_CC_BROWN]
base = "brown"

[STR_PALETTE_CC_DARK_BLUE]
base = "dark blue"

[STR_PALETTE_CC_GREY]
base = "grey"

[STR_PALETTE_CC_LIGHT_BLUE]
base = "light blue"

[STR_PALETTE_CC_MAUVE]
base = "mauve"

[STR_PALETTE_CC_PALE_GREEN]
base = "pale green"

[STR_PALETTE_CC_PINK]
base = "pink"

[STR_PALETTE_CC_PURPLE]
base = "purple"

[STR_PALETTE_CC_YELLOW]
base = "yellow"

# ground
[STR_NAME_GROUND_TYPE_ASPHALT]
base = "asphalt"

[STR_NAME_GROUND_TYPE_COBBLE]
base = "cobble"

[STR_NAME_GROUND_TYPE_DIRT]
base = "dirt"

[STR_NAME_GROUND_TYPE_GRAVEL]
base = "gravel"

[STR_NAME_GROUND_TYPE_PAVEMENT]
base = "pavement"

# rail stations
[STR_NAME_STATION_CLASS_TOWN]
base = "Town stations"

[STR_NAME_STATION_CLASS_FREIGHT]
# CABBAGE - "Freight, not industry" - needs metaclass adjusted?  Industry is the coloured sheds?
base = "Freight stations ({STRING})"

[STR_NAME_STATION_CLASS_INDUSTRY]
base = "Industry buildings ({STRING})"

# road stops
[STR_NAME_ROAD_STOP_CLASS_TOWN]
base = "Town stop"

[STR_NAME_ROAD_STOP_CLASS_FREIGHT]
base = "Freight stop ({STRING})"

[STR_NAME_ROAD_STOP_CLASS_INDUSTRY]
base = "Industry buildings ({STRING})"

# objects
[STR_NAME_OBJECT_CLASS_TOWN]
base = "Town facilities"

[STR_NAME_OBJECT_CLASS_FREIGHT]
base = "Freight facilities ({STRING})"

[STR_NAME_OBJECT_CLASS_INDUSTRY]
base = "Industry buildings ({STRING})"

# station names, keep alphabetised by ID

[STR_NAME_STATION_BOILER_HOUSE_OFFICE]
base = "Boiler house & offices"

[STR_NAME_STATION_BOOKING_OFFICE]
base = "Booking office"

[STR_NAME_STATION_BOOKING_OFFICE_SMALL]
base = "Small booking office"

[STR_NAME_STATION_CARGO_VISIBLE_FREIGHT]
base = "VISIBLE CARGO"

[STR_NAME_STATION_CARGO_VISIBLE_TOWN]
base = "VISIBLE CARGO"

[STR_NAME_STATION_CEMENT_SILO]
base = "Cement silo"

[STR_NAME_STATION_CONCOURSE_1]
base = "Passenger concourse"

[STR_NAME_STATION_DISPATCHERS_OFFICE]
base = "Dispatcher's office"

[STR_NAME_STATION_FLOOD_LOADER_SILO]
base = "Flood loader silo"

[STR_NAME_STATION_FOUNDRY_BUILDINGS]
base= "Foundry building"

[STR_NAME_STATION_HARBOUR_CRANE]
base = "Harbour crane"

[STR_NAME_STATION_HOTEL]
base = "Hotel"

[STR_NAME_STATION_HUTS]
base = "Hut"

[STR_NAME_STATION_MINE_BUILDINGS]
base = "Mine building"

[STR_NAME_STATION_PARCELS_OFFICE]
base = "Parcels office"

[STR_NAME_STATION_TEST]
base = "CABBAGE"

[STR_NAME_STATION_TIPPLE]
base = "Tipple"

[STR_NAME_STATION_WAREHOUSE_TOWN]
base = "Warehouse"


