[GLOBAL_PRAGMA]
grflangid = "0x01"
plural = "0"

[STR_GRF_DESCRIPTION]
base = "CABBAGE"

["# {ORANGE}FIRS Industry Replacement Set{}{BLACK}Brought to you by andythenorth, FooBar, planetmaker, Terkhen and Yexo, with help from many others. {SILVER}See readme for more information, including how to use CHIPS. {BLACK}License"]
base = "GPL v2."

[STR_NAME_STATCLASS]
base = "CABBAGE"

[STR_NAME_STATION]
base = "CABBAGE"
