[GLOBAL_PRAGMA]
grflangid = "0x01"
plural = "0"

[STR_GRF_DESCRIPTION]
base = "CABBAGE"

[STR_CABBAGE]
base = "CABBAGE"

["# {ORANGE}FIRS Industry Replacement Set{}{BLACK}Brought to you by andythenorth, FooBar, planetmaker, Terkhen and Yexo, with help from many others. {SILVER}See readme for more information, including how to use CHIPS. {BLACK}License"]
base = "GPL v2."

# company colours
[STR_PALETTE_USE_DEFAULT]
base = "Company colour"

[STR_PALETTE_CC_GREY]
base = "Grey"

[STR_PALETTE_CC_PINK]
base = "Pink"

[STR_PALETTE_CC_PALE_GREEN]
base = "Green"

[STR_PALETTE_CC_BROWN]
base = "Brown"

# ground
[STR_NAME_GROUND_TYPE_ASPHALT]
base = "(asphalt)"

[STR_NAME_GROUND_TYPE_COBBLE]
base = "(cobble)"

[STR_NAME_GROUND_TYPE_DIRT]
base = "(dirt)"

[STR_NAME_GROUND_TYPE_GRAVEL]
base = "(gravel)"

[STR_NAME_GROUND_TYPE_PAVEMENT]
base = "(pavement)"

# rail stations
[STR_NAME_STATION_CLASS_TOWN]
base = "Stations (pavement)"

[STR_NAME_STATION_CLASS_INDUSTRY]
base = "Stations {STRING}"

[STR_NAME_STATION_CLASS_SPEC]
base = "CABBAGE {STRING}"

# road stops
[STR_NAME_ROAD_STOP_CLASS_TOWN]
base = "Road stops (pavement)"

[STR_NAME_ROAD_STOP_CLASS_INDUSTRY]
base = "Road stops {STRING}"

[STR_NAME_ROAD_STOP_CLASS_SPEC]
base = "CABBAGE {STRING}"

# objects
[STR_NAME_OBJECT_CLASS_TOWN]
base = "Station facilities (pavement)"

[STR_NAME_OBJECT_CLASS_INDUSTRY]
base = "Station facilities {STRING}"

[STR_NAME_OBJECT_CLASS_SPEC]
base = "CABBAGE {STRING}"

# station names, keep alphabetised by ID

[STR_NAME_STATION_BOILER_HOUSE_OFFICE]
base = "Boiler house & offices"

[STR_NAME_STATION_BOOKING_OFFICE]
base = "Booking office"

[STR_NAME_STATION_BOOKING_OFFICE_SMALL]
base = "Small booking office"

[STR_NAME_STATION_CARGO_VISIBLE_INDUSTRY]
base = "VISIBLE CARGO"

[STR_NAME_STATION_CARGO_VISIBLE_TOWN]
base = "VISIBLE CARGO"

[STR_NAME_STATION_CEMENT_SILO]
base = "Cement silo"

[STR_NAME_STATION_CONCOURSE_1]
base = "Passenger concourse"

[STR_NAME_STATION_DISPATCHERS_OFFICE]
base = "Dispatcher's office"

[STR_NAME_STATION_FLOOD_LOADER_SILO]
base = "Flood loader silo"

[STR_NAME_STATION_FOUNDRY_BUILDINGS]
base= "Foundry building"

[STR_NAME_STATION_HARBOUR_CRANE]
base = "Harbour crane"

[STR_NAME_STATION_HOTEL]
base = "Hotel"

[STR_NAME_STATION_HUTS]
base = "Hut"

[STR_NAME_STATION_MINE_BUILDINGS]
base = "Mine building"

[STR_NAME_STATION_PARCELS_OFFICE]
base = "Parcels office"

[STR_NAME_STATION_TEST]
base = "CABBAGE"

[STR_NAME_STATION_TIPPLE]
base = "Tipple"

[STR_NAME_STATION_WAREHOUSE_TOWN]
base = "Warehouse"


